const mongoose = require('mongoose')

const reqString = {
    type: String,
    required: true
}

const singleNotification = mongoose.Schema({
    // user reponsible for notification
    _id: reqString,
    // action that caused notification
    // like - reply - repost - follow
    action: reqString, 
        // post in question
    postID: reqString
})

const interactUserSchema = mongoose.Schema({
    // id name (generated by time + time)
    _id: reqString,
    // displayname
    displayname: reqString,
    // username
    username: reqString,
    // password
    password: reqString,
    // array of post id's
    posts: [ reqString ],
    // array of your likes posts id's
    likes: [ reqString ],
    // array of saved posts id's
    saves: [ reqString ],
    // all new notifcations
    newNotification: [ singleNotification ],
    // make sure theres not to many at once
    oldNotifications: [ singleNotification ],
    // array of viewed posts
    viewedPosts: [ reqString ]
});

module.exports = mongoose.model('interact-user-old', interactUserSchema)